### ISSUE TITLE
"How to hide .Net Core console?" Can you add it to wiki? I think some people may need this.

### ISSUE THREAD

**Issue by maikebing** [mattkol/Chromely#11]
https://stackoverflow.com/questions/45200378/how-to-hide-kestrel-console

editbin.exe /subsystem:windows  cefglue_winapi_netcoredemo.exe

Can you add it to wiki? I think some people may need this.

**Comment by mattkol** [comment]
Will look into it.
Thank you.

**Comment by mattkol** [comment]
Done!

**Comment by mattkol** [comment]
Please check [How to Hide .NET Core Console](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core)#how-to-hide-net-core-console) for more info.
