### ISSUE TITLE
bind cefHost window size to parent window size

### ISSUE THREAD

**Issue by BrannonKing** [mattkol/Chromely#12]
Please add a mechanism to easily bind the internal CEF host's size to the parent window's size such that the CEF host resizes with the parent.

**Comment by mattkol** [comment]
Are you experiencing some lags or delays or it does not work at all?

This is already implemented, please see a sample of [ResizeWindow method](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefGlue.Winapi/Browser/CefGlueBrowser.cs) in CefGlue.

If you are creating a Linux app, there are a few things that are not working yet and are pending.
Please [see](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)#not-working-yet).

**Comment by BrannonKing** [comment]
It doesn't work at all. I followed the instructions here: 
https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core)

The class you pointed me to isn't referenced directly in those instructions. I'm not sure if it is used behind the scenes.

**Comment by mattkol** [comment]
This was discussed in issue #5. So I assume the guide may have been useful then, so I am not sure if I am missing a major step.

Please make sure you have .NET Core 2.0 installed on your machine. Or you can try building the .NET version first. They all have same code base.

I will also suggest you try build the [demo](https://github.com/mattkol/Chromely/tree/master/src/Demos/Chromely.CefGlue.Winapi.netCoreDemo) or run a  published  self-contained .NET app - [cefglue_winapi_netcoredemo.exe](https://github.com/mattkol/Chromely/tree/master/Demos/CefGlue_netCore_win10-x64).  
Remember that in either cases you have to download the CEF binaries. Please check step 9 in the guide.

I just did that on my local machine. Please see the attached screen capture.
![issue12](https://user-images.githubusercontent.com/18384207/39082878-4cd634a6-4528-11e8-9708-a411c38f0195.gif)
