### ISSUE TITLE
I Can not run the Demo

### ISSUE THREAD

**Issue by shilf** [mattkol/Chromely#13]
1. I have download cef3.3359_window64 
2. Copy all files from /Release to the demo folder.
   Copy all files from /Resources to demo folder.
3.when I run cefglue_winapi_demo.exe , it is a blank

**Comment by shilf** [comment]
![_20180511144705](https://user-images.githubusercontent.com/1725360/39910500-35b64efc-552a-11e8-887d-2eb9133e2ff5.png)
Copy all files from /Release to the demo folder.
Copy all files from /Resources to demo folder.
When I run  cefglue_winapi_demo.exe
![_20180511144833](https://user-images.githubusercontent.com/1725360/39910556-6969db42-552a-11e8-8d64-ea4b14d838d4.png)

**Comment by mattkol** [comment]
Please see the [guide #7](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi) 
*"Get Cef binaries from download page. Base Chromium version 59 or above (64-bit) with version matching Chromely.Unofficial.CefGlue.NetStd installed."*

Current version of Chromely.Unofficial.CefGlue.NetStd is 64.0.3282.119.

So you will need cef_binary_3.3282.1741.gcd94615_windows64_minimal.

Please let me know if you need more info.

**Comment by mattkol** [comment]
Also the log would have more info.

**Comment by shilf** [comment]
I have download cef_binary_3.3282.1741.gcd94615_windows64_minimal.
and Copy all files from /Release to the demo folder. Copy all files from /Resources to demo folder.

debug.log
[0512/005240.311:WARNING:resource_bundle.cc(368)] locale_file_path.empty() for locale 
[0512/005240.311:ERROR:main_delegate.cc(683)] Could not load locale pak for en-US
[0512/005240.311:ERROR:main_delegate.cc(690)] Could not load cef.pak
[0512/005240.311:ERROR:main_delegate.cc(707)] Could not load cef_100_percent.pak
[0512/005240.311:ERROR:main_delegate.cc(716)] Could not load cef_200_percent.pak
[0512/005240.311:ERROR:main_delegate.cc(726)] Could not load cef_extensions.pak
[0512/005240.311:ERROR:content_client.cc(272)] No data resource available for id 101

**Comment by mattkol** [comment]
I think I see where the confusion might be. The statement should be **"copy all files and folders ..."**.  I will make that change in the wiki. Sorry about that.

It looks like the **"locales"** folder is missing.

This should be folder layout after the cef binaries merge:

![cef_merged_binaries](https://user-images.githubusercontent.com/18384207/39949509-2204408e-5549-11e8-8bf9-1e38585abd5e.png)

This should be the folder layout when added to the bin folder:

![cefglue_binaries](https://user-images.githubusercontent.com/18384207/39949522-33642a06-5549-11e8-8ef1-c525f793619c.png)

**Comment by shilf** [comment]
![_20180512135509](https://user-images.githubusercontent.com/1725360/39954113-3451117e-55ec-11e8-9d69-da75c35569f6.png)
but still 
[0512/135201.468:WARNING:resource_bundle.cc(368)] locale_file_path.empty() for locale 
[0512/135201.468:ERROR:main_delegate.cc(683)] Could not load locale pak for en-US
[0512/135201.468:ERROR:main_delegate.cc(690)] Could not load cef.pak
[0512/135201.468:ERROR:main_delegate.cc(707)] Could not load cef_100_percent.pak
[0512/135201.468:ERROR:main_delegate.cc(716)] Could not load cef_200_percent.pak
[0512/135201.468:ERROR:main_delegate.cc(726)] Could not load cef_extensions.pak
[0512/135201.484:ERROR:content_client.cc(272)] No data resource available for id 101

**Comment by shilf** [comment]
I suggest author download it from github，and then run cefglue_winapi_demo.exe
I download cef_binary_3.3282.1741.gcd94615_windows64_minimal. and try it failed

**Comment by mattkol** [comment]
Since you have all the files the application is complaining about, it **may be a permission issue** on your computer.

But first what Windows version are you running? I am running Windows 10.
Also the "locales" folder should have all the pak files.

I just downloaded the repo and both CefGlue demos ran successfully:

* CefGlue_netCore_win10-x64 (add the merged cef binaries and run "cefglue_winapi_netcoredemo.exe")
* CefGlueWin64

You can try the self-contained .NET Core build - CefGlue_netCore_win10-x64.

Another alternative is to try the [CefSharp](https://github.com/mattkol/Chromely/tree/master/src/Demos/Chromely.CefSharp.Winapi.Demo) project. This will download the required cef binaries when you build the project and references are restored.

**Comment by mattkol** [comment]
Also if you have .NET Core 2.0 installed you can try the cli:
[dotnet-cli-Starter-Template](https://github.com/mattkol/Chromely/wiki/dotnet-cli-Starter-Template)

**Comment by mattkol** [comment]
I will close this for now. Please reopen this or start a new thread if you have more questions.
