### ISSUE TITLE
CPU's consumption

### ISSUE THREAD

**Issue by stefan2410** [mattkol/Chromely#14]
Hi,  nice and interesting open source project, thank you!
I did run the demos and compiled my .Net Core application following the instructions in the [Getting-Started-CefGlue-Winapi-(.NET-Core)](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core))

I noticed that in all precompiled demos and in my new project,   the CPU's consumption is 30-35%  continuously.
![crhomelyappt_2](https://user-images.githubusercontent.com/1259393/40307673-2a8b7b30-5d0c-11e8-9b09-7af77569b5f3.png)

What provokes such high consumption?
another question.  In case of "multi-process", I don't understand what path to give 
 
             .WithCustomSetting(CefSettingKeys.BrowserSubprocessPath, path_to_sunprocess)

Thanks!

**Comment by mattkol** [comment]
Thanks for the compliment.

On the consumption, I kind of lost track of that over time. Thanks for pointing it out. I will investigate.

On the "multi-process" issue, my comment was referring to setting path to a separate process.
.NET Core compiles  to dll not an exe. For multi-process, Cef requires the use of the main exe or a separate subprocess. So my comment was highlighting ways to achieve multi-process in .NET Core apps as the dll will not be recognized as a subprocess.

https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-separate-sub-process-executable

For .NET Core apps, to achieve multi-process, my suggestions are:
1. Do a self-contained build that will create an exe.
2. Leave the app as dll and add a separate subprocess.

**Comment by mattkol** [comment]
I was able to track the CPU consumption to the external [WinApi lib](https://github.com/prasannavl/WinApi). 
I am investigating and making changes to that.

Meanwhile, this is the gtk CPU consumption.
![image](https://user-images.githubusercontent.com/18384207/40351293-0beb2de2-5d7a-11e8-8924-d81bbf2ccde8.png)

**Comment by mattkol** [comment]
**Thanks a lot for pointing this out!**

Found it. This was introduced in [HostEventLoop](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefSharp.Winapi/HostEventLoop.cs) when I implemented external pumping. This uses Win32 PeekMessage, while the previous one uses Win32 GetMessage. I will do more research to see why that is an issue.

Please see differences [here](https://github.com/prasannavl/WinApi/blob/master/WinApi/Windows/EventLoop.cs).

Meanwhile, please replace:
````csharp
class Program
{
   static int Main(string[] args)
   {
      ----
         return new HostEventLoop().Run(window);
     }
  }
}
````
With:
````csharp
class Program
{
   static int Main(string[] args)
   {
      ----
         return new EventLoop().Run(window);
     }
  }
}
````
CPU usage after change:
![image](https://user-images.githubusercontent.com/18384207/40354757-987fb98c-5d82-11e8-8431-685d33876bbe.png)
