### ISSUE TITLE
Getting to run Chromely with GTK on windows and linux

### ISSUE THREAD

**Issue by maulwuff** [mattkol/Chromely#15]
In your demo on "Getting Started CefGlue Gtk (Linux)" you write:
```
var factory = WinapiHostFactory.Init();
            using (var app = new CefGlueBrowserHost(config))
```

this class seems to be from `CefGlue.WinApi`.
Is `WinApi` and `CefGlue.WinApi` required to run on linux? the wiki page doesn't mention them.

Even with those 2 packages, it won't run on windows, because Cef is missing. 
So I added cef like written further down on the wiki page.

I then installed the gtk+ 64bit runtime in v2.24 from 
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

(installing the 32bit version will throw BadImageFormatException)

With this installed, I got this exception:
Exception thrown: 'System.DllNotFoundException' in Chromely.CefGlue.Gtk.dll:
'gtksharpglue-2'

After googling I found, that I need Gtk# to be installed from http://www.mono-project.com/download/stable/

Now I get BadImageFormatException agai, presumably, because Gtk# doesn't ship a 64bit version.
`   at Chromely.CefGlue.Gtk.ChromeHost.NativeMethods.Win.gtksharp_gtk_widget_get_window(IntPtr widget)`

Is 64bit required for Chromely or would it run in32bit mode, too?

**Comment by mattkol** [comment]
This was no longer needed. Early versions had Chromely.Core dependent on WinApi dll.

```
var factory = WinapiHostFactory.Init();
            using (var app = new CefGlueBrowserHost(config))
```

Now removed, should be:
```
            using (var app = new CefGlueBrowserHost(config))
```

Thanks for pointing this out.

**Comment by mattkol** [comment]
Gtk on Windows has only been tested for 32bit.

I made it more obvious:
10. **Download Mono - 32 bit** gtk binaries from [Mono Project](http://www.mono-project.com/download/) and copy necessary files to the bin folder.

So if you follow the guide, you only need 2 downloads - the gtk 32 bit from mono project and cef binaries..

**Comment by mattkol** [comment]
Gtk on Linux has only been tested for 64bit.
This is what .NET Core supports for now.
Most Linux  distros have gtk already installed. If this is the case, you only need the Cef binaries downloaded.

Please find more details in the guide.

**Comment by maulwuff** [comment]
> "gtksharpglue-2"
this one is included in gtk# msi.

> Gtk on Linux has only been tested for 64bit.
> This is what .NET Core supports for now.

you mean, .net core only supports 64bit on linux?

This would mean that I have to ship 2 different cef blobs to be cross platform runable.

can you consider changing how cef is "deployed"?
maybe to have it located in subfolders like cef_win32, cef_win64, cef_linux32 etc
this would keep the bin folder clean and make it easier to switch own and third party dlls.

**Comment by mattkol** [comment]
I just added required  [gtk binaries](https://github.com/mattkol/Chromely/tree/master/binaries/gtk32bit) to the repo.

Updated guide:
10. Get required [gtk binaries](https://github.com/mattkol/Chromely/tree/master/binaries/gtk32bit) or **Download Mono 32-bit** gtk binaries from [Mono Project](http://www.mono-project.com/download/) and copy necessary files to the bin folder.

**Comment by mattkol** [comment]
Yes, no support yet for 32-bit on Linux. Not sure if Roadmap is updated yet.
[Stackoverflow discussion](https://stackoverflow.com/questions/43405642/is-installing-net-core-on-32bit-ubuntu-possible).

The difficulty with GTK for now is on Windows - 64bit has little support, on Linux, .NET Core has no support yet for 32bit. But I believe as .NET Core gains traction things will get easier.

For pure cross-platform I have toyed with Nana C++, Libui - they all will work but they will require more work and more dependencies that I am trying to avoid. I want to stay as close to the core as possible.

**Comment by mattkol** [comment]
_can you consider changing how cef is "deployed"?
maybe to have it located in subfolders like cef_win32, cef_win64, cef_linux32_ 

Sure, that would be a good idea. I can look into that. Likely will be a weekend task.
