### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by icosahedron** [mattkol/Chromely#17]
Is support for macOS planned?

**Comment by mattkol** [comment]
No support yet for macOS, but the plan is to make Chromely truly cross-platform. The only limitation now is the required skill. I have never developed on macOS before and do not currently have the bandwidth to learn enough.

However, as I have mentioned to others in the past, help and contributions are welcome.

**Comment by mattkol** [comment]
@icosahedron  please see - https://github.com/chromelyapps/Chromely/issues/135
