### ISSUE TITLE
I can't isntall Chromely using nugget!

### ISSUE THREAD

**Issue by Donaut** [mattkol/Chromely#2]
When I click on the installation. The error message is i use the wrong .net version (4.6.1)!

**Comment by mattkol** [comment]
I believe you are referring to CefGlue lib on nuget. This is built against .NET Standard 2.0 and yes would require 4.6.1 client - https://docs.microsoft.com/en-us/dotnet/standard/net-standard.

Please see if you can run any of the demos -CefGlue or CefSharp and to see how the project setup is - [Demos](https://github.com/mattkol/Chromely/tree/master/Demos). I am still working on the documentation, but there should be enough info on CefGlue in [Getting Started](https://github.com/mattkol/Chromely/wiki/Getting-Started).

Please also note that you do not need to use the Chromely CefGlue in all situationns. This is only required if you want to build a .NET Core app. You can build afresh against other .NET CefGlue nuget libs.
