### ISSUE TITLE
DI for JsonMapper - Logger

### ISSUE THREAD

**Issue by stefan2410** [mattkol/Chromely#20]
How can I change the IJsonMapper with DI  (with other JSON library or even other protocol)?
The same for the Logger.  
Thanks!

**Comment by mattkol** [comment]
LitJson JsonMapper is  provided as default and is not intended to be replaced.

You can however, add additional JsonMapper/Serializer - as many as you like.

The IOC container is available anytime, so you can register the mapper anytime you like. Sample can be:

````csharp
 IoC.RegisterSingleton(type1, key1, new JsonMapperClass1());
 IoC.RegisterSingleton(type2, key2, new JsonMapperClass2());
````

The logger can be replaced. Replacement is allowed for during registration.
**Note that the logger must implement the [IChromelyLogger](https://github.com/mattkol/Chromely/blob/master/src/Chromely.Core/IChromelyLogger.cs) interface,

````csharp
IChromelyLogger logger = new NewLogger();
ChromelyConfiguration config = ChromelyConfiguration
                              .Create()
                               ....
                              .WithLogger(logger)
````
Please see more info in [Configuration](https://github.com/mattkol/Chromely/wiki/Configuration).
