### ISSUE TITLE
Unable to load DLL 'libcef'

### ISSUE THREAD

**Issue by Fxztam** [mattkol/Chromely#22]
Tried >dotnet restore => works well.

C:\Works\Work-Chromely>dotnet run
2018-05-31 20:48:05.258 [ERROR] Oops! Something went wrong.     Unable to load DLL 'libcef':
.
 (Exception from HRESULT: 0x8007007E)        at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Chromely.CefGlue.Winapi.ChromeHost.CefGlueBrowserHost.OnCreate(CreateWindowPacket& packet)
   at WinApi.Windows.Packetizer.ProcessCreate(WindowMessage& msg, EventedWindowCore window)
   at WinApi.Windows.WindowCore.WindowProc(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
..
Missing some pre-conditions ??

**Comment by mattkol** [comment]
Yes, you are.

You need to download the Cef binaries,

There is a link at the top of the sub heading   [dotnet cli demo template install](https://github.com/mattkol/Chromely/wiki/dotnet-cli-Starter-Template).

I have also made it more obvious.

If you want to try Chromely without downloading Cef binaries, you can try the CefSharp demo.

**Comment by biohazard999** [comment]
@mattkol I've also got troubles in the first place with the Cef binaries, are you cool with a Cake script for the build (or the demos) to fetch them automatically? Then I'll send you another PR.

**Comment by mattkol** [comment]
That will be fantastic!

**Comment by Fxztam** [comment]
Don't know I ignore the step 4, Sorry.

Downloaded the cef_binary_3.3359.1774.gd49d25f_windows64 now,
but cannot find the exe in my project folder ..
> Chromely.CefGlue.Win -> C:\Works\Work-Chromely\bin\Debug\netcoreapp2.0\cefglue_winapi_netcoredemo.dll
was generate with dotnet build. 
(copy Resource & Realese into this folder does not work)

**Comment by mattkol** [comment]
The cli is not updated to CefGlue v65 yet.
You need: cef_binary_3.3282.1741.gcd94615_windows64
There is a link in the guide - https://github.com/mattkol/Chromely/wiki/CefGlue-Application-Layout
    
 #### Versions Map

    | Chromely.CefGlue.Winapi | Chromely.Unofficial.CefGlue.NetStd | Required Cef Binary |
    | :---         | :---         | :--- |
    | 64.0.0.0 | 64.0.3282.119    | 3.3282.1741.gcd94615 |
    | 65.0.0.0 | 65.0.3325.181    | 3.3325.1751.ge5b78a5 |

.NET Core builds to .dll.
To get the exe, you have to publish it. Please see more info - [Getting Started CefGlue Winapi (.NET Core)](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core)).
