### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by biohazard999** [mattkol/Chromely#23]
Currently I'm working on a project to bring blazor to desktop: [blaster](https://github.com/biohazard999/Blaster/)

Good to see a lightweight alternative to electron in c# 👍 

But I've troubles where to catch up to serve the blazor files. Basically I need just a hint where to handle the mime types chromium serves for the example IIS config.

Thats the output of the blazor publish:
``` xml

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <remove fileExtension=".dll" />
      <remove fileExtension=".json" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".dll" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" /> 
    </staticContent>
    <httpCompression>
      <dynamicTypes>
        <add mimeType="application/octet-stream" enabled="true" />
        <add mimeType="application/wasm" enabled="true" />
      </dynamicTypes>
    </httpCompression>
    <rewrite>
      <rules>
        <rule name="Serve subdir">
          <match url=".*" />
          <action type="Rewrite" url="Blaster.Blazor\dist\{R:0}" />
        </rule>
        <rule name="SPA fallback routing" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
          </conditions>
          <action type="Rewrite" url="Blaster.Blazor\dist\" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

Awesome project :)

**Comment by mattkol** [comment]
This is going to be exciting! Love it!

**Comment by mattkol** [comment]
Chromely really should be concerned with the final bundle and needs an entry html.

So, I see 2 options concerning Blaster - Resource loading and file protocol (file:///) - more info @ [Loading Html](https://github.com/mattkol/Chromely/wiki/Loading-Html).

The work here will be in resource loading. Please see samples - [CefSharp](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefSharp.Winapi/Browser/Handlers/CefSharpResourceSchemeHandler.cs), [CefGlue](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefGlue.Winapi/Browser/Handlers/CefGlueResourceSchemeHandler.cs).

You need to see how these are registered in [Configuration](https://github.com/mattkol/Chromely/wiki/Configuration).

The mime types Chromely uses in those two handlers are from a comprehensive list from CefSharp repo. You can look at the list and any mime type missing can be added - [the list](https://github.com/mattkol/Chromely/blob/master/src/Chromely.Core/Helpers/MimeMapper.cs).

I will find time to try Blastor at some point and give more hints I find as it relates to Chromely.

**Comment by biohazard999** [comment]
Thanks for the hint!
Almost got it working https://github.com/biohazard999/Blaster/blob/master/src/Blaster.Chromely/Program.cs

Do you have another hint how to show the devtools in Chromely on startup, so i can track the network stuff? It seams I am missing something, so blazor can't find a specifc dll.

**Comment by biohazard999** [comment]
Thanks for the response, I'll give it a shot :)

**Comment by biohazard999** [comment]
Awesome!

```cs
 public class BlasterLifeSpanHandler : CefLifeSpanHandler
   using System;
using Xilium.CefGlue;

namespace Blaster.Chromely.Handlers
{
    public class BlasterLifeSpanHandler : CefLifeSpanHandler
    {
        protected override void OnAfterCreated(CefBrowser browser)
        {
            base.OnAfterCreated(browser);

            var wi = CefWindowInfo.Create();
            var host = browser.GetHost();
            wi.SetAsPopup(IntPtr.Zero, "DevTools");
            host.ShowDevTools(wi, new DevToolsWebClient(), new CefBrowserSettings(), new CefPoint(0, 0));
        }

        /// <summary>
        /// The dev tools web client.
        /// </summary>
        private class DevToolsWebClient : CefClient
        {
        }
    }
}
```

```cs
ChromelyConfiguration config = ChromelyConfiguration
                                          .Create()
                                          .RegisterCustomHandler(CefHandlerKey.LifeSpanHandler, typeof(BlasterLifeSpanHandler));
```

did the trick 👍

**Comment by mattkol** [comment]
It is better than my approach.
But!!!

This will work all the time, if this is the only context menu handler.  What the registration does is to remove the default handler and set a new one. Not sure you can have more than one context menu handler. If this is what is intended, great!

**Comment by biohazard999** [comment]
I'm not getting into the nitty gritty details right now, for research it's good enough right now :)
But if i understand the source right, i'm not dealing with the context menu  at all?
So maybe I'm ending with 2 devtools if i invoke it via context menu, but at the moment i don't care.
Need to get routing working :)

**Comment by mattkol** [comment]
> But if i understand the source right, i'm not dealing with the context menu at all?
That is what I am trying to point out. That is the only context menu handler. So this can be used for both purposes. Just to draw your attention to that.
All looks great to me. 👍

**Comment by mattkol** [comment]
For blazor support, please see - https://github.com/chromelyapps/demo-projects/tree/master/blazor.
