### ISSUE TITLE
how to request url address?

### ISSUE THREAD

**Issue by PlumpMath** [mattkol/Chromely#3]
window... request url ("www.google.com")?
thanks.

**Comment by mattkol** [comment]
@PlumpMath 

Thanks for bringing this up. Was one scenario, I did not test earlier.

I have tried 4 different options:

*** Please always use url with scheme (http or https). 
Without the scheme, it will open a new Chromely app with blank view.
https://google.com ***Correct
www.google.com   ***Will fail

1. 
````csharp
window.open('https://google.com')

This will open google in an external browser.
````

2. 
````csharp
window.open('https://google.com', '_blank');

This will open google in an external browser. Same as 1.
````

3. 
````csharp
 window.open('https://google.com', '_self');

This will open google in the application window. If this is what you want you have to program for navigation from this view.
````

4. 
````csharp
 window.open('https://google.com', '_self');
 window.RegisterExternalUrlScheme(new UrlScheme("https://google.com", true));

and registering the scheme and host as external url, will always open in an external window.

````
[For 4 please see url registration](https://github.com/mattkol/Chromely/wiki/External-Url-Registration)


Please let me know if this is helpful.

**Comment by mattkol** [comment]
Thank you. Will close.
