### ISSUE TITLE
Make Chromely.Cef.Redist working for dotnet core

### ISSUE THREAD

**Issue by biohazard999** [mattkol/Chromely#30]
Currently the Chromely.Cef.Redist does not work for dotnet core correctly.
To do so we need to adjust the targets to respect the RuntimeIdentifiers correctly.

See [Microsoft.NETCore.Platforms](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/)
See [cross-platform-net-core-apps](https://stackify.com/cross-platform-net-core-apps/)
See [rid-catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)

I had no luck getting [Runtimes](https://docs.microsoft.com/de-at/nuget/archive/project-json#runtimes) working. But my knowledge in packing native dependencies cross-platform is limited.

**Comment by mattkol** [comment]
Cef.Redist implementation reverted for now.
