### ISSUE TITLE
Setting a minimum size

### ISSUE THREAD

**Issue by CWolfs** [mattkol/Chromely#36]
How would I go about setting a minimum size for the window?

Thanks!

**Comment by mattkol** [comment]
I have not had time to look at this closely. This is intended to be done using the constructionParams ..
by extending FrameWindowConstructionParams class.

````csharp
class Program
{
   static int Main(string[] args)
   {

     using (var window = factory.CreateWindow(() => new CefGlueBrowserHost(config),
           "chromely", constructionParams: new FrameWindowConstructionParams()))
      {
     }
  }
}
````
Please if this is urgent for you, you can try get more info @ [WinApi](https://github.com/prasannavl/WinApi).

**Comment by CWolfs** [comment]
Thanks for the reply. It's not urgent but I'd like to prevent the user sizing the tool I'm making below a certain size. I'll take a look at what you suggested.

Thanks!
