### ISSUE TITLE
how to pass args from Program.cs to DemoController?

### ISSUE THREAD

**Issue by ors373** [mattkol/Chromely#37]
Hello

I am in need of some help using chromely

I want to give chromely an array of args when calling dotnet run,
and then use those args in the controller.

using the demo,
where would i need to put args in Program.cs,
and how do i call args from within DemoController?

Your assistance would be greatly appreciated

**Comment by CWolfs** [comment]
There might be a more intended way to do it but I incorporate the `Service` approach into my app. This is where any major logic goes into a domain-specific `Service` singleton object. You could adopt this approach for a singleton `ConfigService` too.

```
  public class ConfigService {
    private static ConfigService instance;
    // Store your config variables here

    public static ConfigService getInstance() {
      if (instance == null) instance = new ConfigService();
      return instance;
    }

    // Add none static get / set methods here
```

**Comment by mattkol** [comment]
I prefer @CWolfs approach as that will be a simpler implementation.

But I am assuming that those command line parameters are dynamic/configurable and can be changed by the users.

If that is the case, you may also consider parsing the arguments and use one of these approaches:

1. The singleton class approach to cache the parameters with @CWolfs approach.
2. Register them as instance(s) in the IOC container. The container is avaliable the first time you use it. Then in your controller you can retrieve it.

Both of these must be done before you start the Winapi window. Or during window creation .. at least before assembly scanning.

Before assemblies scanning:

````csharp
class Program
{
   static int Main(string[] args)
   {
     using (var window = factory.CreateWindow(() => new CefGlueBrowserHost(config),
           "chromely", constructionParams: new FrameWindowConstructionParams()))
      {
         ....
         // Scan assemblies for Controller routes 
         window.ScanAssemblies();
         ....
         return new EventLoop().Run(window);
     }
  }
}
````
