### ISSUE TITLE
Could you please do me a favour to tell me how to support html5

### ISSUE THREAD

**Issue by ysh512** [mattkol/Chromely#41]
I rebuild the cefsharp to enable the html5. Then I copy the dll into the project.But it does not work.

**Comment by mattkol** [comment]
You don't have to do anything to support html5. Unless there are specific features that you want that are not yet supported.

Please start with the Demos, there is an option to see what html5/6 features are supported in the demos.

For CefSharp demo - please [see](https://github.com/mattkol/Chromely/tree/master/src/Demos/Chromely.CefSharp.Winapi.Demo).
