### ISSUE TITLE
Opening multiple windows in Chromely

### ISSUE THREAD

**Issue by igloo15** [mattkol/Chromely#43]
Is there a way to open multiple chromely windows? Say for instance I want to open a new link in another chromely window. I have tried using window.open() or links with target _blank but nothing appears to happen. 

If register as externalurl it opens in separate browser but I want it to open in another chromely window. 

Additionally I was thinking of creating a loading screen where I have one window open and then when it closes I open a second main one. Is that possible with chromely?

**Comment by mattkol** [comment]
If you are referring to popups, Chromely does not support popups. Chromely is primary designed for Single Page Applications (SPAs) so only one window is intended.

Is it possible? Yes, it is. You may have to tweak either the CefSharp or CefGlue host to make it a popup - making the new window a child of the parent and launch that in LifeSpanHandler OnBeforePopUp method.
