### ISSUE TITLE
Frameless windows...?

### ISSUE THREAD

**Issue by Thomas-QM** [mattkol/Chromely#44]
I'm sorta a noob but I have no idea how to make the window frameless... I've heard of ``WM_NCHITTEST`` but can't find it in the window flags... thanx

**Comment by mattkol** [comment]
Not quite sure that is the flag you need.

Chromely does not support this feature. I will recommend you look at following links for some guide. 

https://github.com/melak47/BorderlessWindow
https://social.msdn.microsoft.com/Forums/vstudio/en-US/b98c4c06-9581-44d3-8e5a-4adb2316e653/win32-about-styles-how-can-i-do-a-borderless-window?forum=vclanguage

Also you can look at FrameWindowConstructionParams class used when creating the Window.


````csharp
class Program
{
   static int Main(string[] args)
   {
     var factory = WinapiHostFactory.Init();
     using (var window = factory.CreateWindow(() => new CefGlueBrowserHost(config),
           "chromely", constructionParams: new FrameWindowConstructionParams()))
      {
             ------
     }
  }
}
````
Details on FrameWindowConstructionParams class can be found on [WinApi site](https://github.com/prasannavl/WinApi/blob/4b50cb0add45a70816720b41c1a585c6b73dbf79/WinApi/Windows/ConstructionParams.cs). You can override the default.

Please let me know if you need more info.

**Comment by Thomas-QM** [comment]
woah thanks! i got it with just ``WS_POPUP`` :D

**Comment by mattkol** [comment]
Great! Would you like to share your code? May be helpful to others? Thanks.

**Comment by Thomas-QM** [comment]
sure! but its in f# >:)

```fsharp
    let window = factory.CreateWindow(Func<CefGlueBrowserHost> browserinitialize, "apptitle", constructionParams=new FrameWindowConstructionParams())
    window.SetStyle(WindowStyles.WS_POPUP ||| WindowStyles.WS_SYSMENU ||| WindowStyles.WS_MAXIMIZEBOX ||| WindowStyles.WS_MINIMIZEBOX) |> ignore
    
    let mutable windowlocked = false //dont tell anyone else its mutable kthxbai
    windowmsghandler <- (function //this too...
        | Minimize -> window.SetState (ShowWindowCommands.SW_MINIMIZE) |> ignore
        | Restore ->
            if windowlocked then
                window.SetState (ShowWindowCommands.SW_RESTORE) |> ignore
            else
                window.SetState (ShowWindowCommands.SW_MAXIMIZE) |> ignore
                let (_, workrect) = User32Helpers.GetMonitorInfo(User32Methods.MonitorFromWindow(window.Handle, MonitorFlag.MONITOR_DEFAULTTONEAREST))
                printfn " WORK RECT: %A" workrect.WorkRect
                window.SetPosition (workrect.WorkRect) |> ignore
            windowlocked <- not windowlocked
        | Close -> exitprocedure () |> ignore
        | Move (x,y) when not windowlocked ->
            let (x,y) = (int x, int y)
            let rect = window.GetWindowRect ()
            window.SetPosition (new Rectangle(x,y,rect.Width+x, rect.Height+y)) |> ignore
        | Resize (width,height) when not windowlocked ->
            let rect = window.GetWindowRect()
            window.SetPosition(new Rectangle (rect.Left, rect.Top, rect.Right+int width, rect.Bottom+int height)) |> ignore
        | _ -> ()
    )
```

there i just have the window initializer and a simple message handler which handles window messages from the client via a websocket somewhere else...
the windowlocked controls whether the resizing and dragging are locked, which is enabled when the window is maximized
using ``WS_THICKFRAME`` actually provides native resizing, but theres a weird white bar at the top and some other weird stuff which im not sure how to fix (but it might have something to do with the window state)
i was lazy and didnt know how to interrupt the eventloop so i just used a function ;)

heres how it looks in action:

![yey](https://user-images.githubusercontent.com/13261878/45858454-54871500-bd12-11e8-9bf0-d272cba0ea87.gif)

**Comment by mattkol** [comment]
Thank you.
