### ISSUE TITLE
Provide demo binaries

### ISSUE THREAD

**Issue by niutech** [mattkol/Chromely#45]
I am not a .NET developer and I do not have .NET SDK, but I am searching for a lightweight alternative to Electron/NW.js and I want to try out Chromely. However, I cannot find any demo `chromely.exe` binaries for Windows. Can you provide a demo app, running a local HTML file in a subfolder, similar to NW.js?

Thanks!

**Comment by mattkol** [comment]
You can try the demo apps at:

https://github.com/mattkol/Chromely/tree/master/Demos

Note that you still have to download the cef binaries. Please follow the guides provided.

If you go the demo projects route, you don't have to download the cef binaries.

Please let me know if this helps.

**Comment by niutech** [comment]
Thank you. I have successfully run both CefSharp and CefGlue demos. However, CefGlue looks blurry on my HiDPI screen (on the left):

![cefglue - cefsharp](https://user-images.githubusercontent.com/384997/46311818-a1e16d00-c5c3-11e8-9c09-e756343a7ffc.png)

What is more, `cefglue_demo_binaries` is 131 MB and `cefsharp_demo_binaries` is 126 MB including CEF, which is far from being _Lightweight Alternative to Electron_.

**Comment by mattkol** [comment]
Not sure if these are questions or just your observations or both.

1. On CefGlue HiDPI - thanks for pointing that out. I will include it for next release. Was missed.

2. "Lightweight" here is not referring to the final weight of the binaries. It is referring to the lightweight of the framework itself.  Simplicity - simple & less to achieve same, if you may.
