### ISSUE TITLE
Full screen?

### ISSUE THREAD

**Issue by sambengtson** [mattkol/Chromely#48]
This may not exactly be a Chromely issue, but I'm trying to figure out how to create a full screen window.

I've discovered the 

> WS_MAXIMIZE 

flag, but that seems to  only maximize the window within the constraints set by the ChromelyConfiguration.  Is there a built in way to do this?  Thanks.

**Comment by simonbuehler** [comment]
was evaluating this cool project for a kiosk application and this is a hard requirement for a public UI, great work!

**Comment by sambengtson** [comment]
@mattkol Ok cool.  I'll wait for you to implement.  Appreciate the work!

**Comment by mattkol** [comment]
There are two new classes that give options for WindowsState - [CefGlue WindowsState](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefGlue.Winapi/WindowState.cs) and [CefSharp WindowsState](https://github.com/mattkol/Chromely/blob/master/src/Chromely.CefSharp.Winapi/WindowState.cs)

The options are:

Normal
Maximized
Fullscreen

-- example:

````csharp
                var factory = WinapiHostFactory.Init("chromely.ico");
                using (var window = factory.CreateWindow(
                    () => new CefSharpBrowserHost(config),
                    "chromely",
                    width: config.HostWidth,
                    height: config.HostHeight,
                    constructionParams: WindowState.Fullscreen))
                {
                    ...
                }
            }
````

Please let me know if this works. I should have sometime to make a release for newer versions over the weekend that should include this.

**Comment by sambengtson** [comment]
@mattkol Thanks this looks good.  I cloned the repo and an using the new WindowState but it still seems to use the config set by my ChromelyConfiguration.  Is there something additional that I need to do with this?

**Comment by sambengtson** [comment]
@mattkol Got it.  It appears to be working great!

**Comment by WSpadaro** [comment]
@mattkol I am also trying to use Chromely to create a kiosk type product but it will be deployed on Linux. Is there an equivalent way to make the window full-screen using CefGlue Gtk Linux?

**Comment by mattkol** [comment]
@WSpadaro the CefGlue Gtk Linux part of the project has been stagnant for a while, as I see not much interest in it. Interestingly it was where I spent the most time at the beginning because my day job is on .NET. I will like for someone with expertise on Linux to help push it forward, I have had a few promises but nothing concrete yet. Same for macOS.

I currently do not have that much bandwidth to get the Linux part to the finish line. Help is appreciated and PR will be accepted.  Same for the full screen.

**Comment by mattkol** [comment]
@WSpadaro  what I can try is try apply the full screen option to the windows gtk version. Then you can see if it works for you on Linux. Will be a weekend try.

**Comment by WSpadaro** [comment]
@mattkol If we can get the full screen working I will put some time into testing the linux part and if needed would try to issues PRs where appropriate

**Comment by mattkol** [comment]
@WSpadaro the WindowState mode is now done. The options are [here](https://github.com/mattkol/Chromely/blob/master/src/Chromely.Core/Host/WindowState.cs).

````csharp
      ChromelyConfiguration config = ChromelyConfiguration
                                    .Create()
                                    .WithHostMode(WindowState.Fullscreen)
                                    .WithHostTitle("chromely")
                                    .WithAppArgs(args)
                                    .WithHostSize(1000, 600)
                                    .WithStartUrl(startUrl);

     using (var app = new ChromelyApplication(config))
     {
          return app.Run(args);
     }
````
Sample demos -  [Win](https://github.com/mattkol/Chromely/tree/master/src/Demos/Chromely.CefGlue.Gtk.Win.Demo) and [Linux](https://github.com/mattkol/Chromely/tree/master/src/Demos/Chromely.CefGlue.Gtk.Linux.Demo). 
Guide  - [Win](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Win)) and [Linux](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)).

Note: You can also try the the nuget packages - [Chromely.CefGlue.Gtk.66.0.0-beta.nupkg & Chromely.Core.0.9.2.nupkg](https://github.com/mattkol/Chromely/tree/master/binaries). With these you don't have to install the cef binaries manually, Never tested on Linux. Works well on Windows. By next weekend I should have the packages uploaded to nuget.org.

Please let me know what you find with Linux testing.

**Comment by WSpadaro** [comment]
I have tested the code changes with Linux using the following configurations:
```
            string startUrl = "http://www.google.com";
            ChromelyConfiguration config = ChromelyConfiguration
                                          .Create()
                                          .WithHostTitle("chromely")
                                          .WithAppArgs(args)
                                          .WithHostSize(1000, 600)
                                          .WithStartUrl(startUrl)
                                          .WithHostMode(Chromely.Core.Host.WindowState.Fullscreen)

                                           //Set multi-threaded_message_loop false
                                           //only supported on windows
                                           .WithCustomSetting(CefSettingKeys.MultiThreadedMessageLoop, false)
                                           //.WithCustomSetting(CefSettingKeys.SingleProcess, true)

                                           .WithCommandLineArg("disable-gpu", "1")
                                           .WithCommandLineArg("disable-gpu-compositing", "1")
                                           .WithCommandLineArg("disable-smooth-scrolling", "1")
                                           .WithCommandLineArg("no-sandbox", "1");

            using (var app = new ChromelyApplication(config))
            {
                return app.Run(args);
            }
```
When I run on Linux a full-screen window pops up as desired; however, the browser never loads and the terminal outputs the following errors:
wesley@J4005B:~/Shared/Chromely/publish$ ./ChromelyLinux
[1203/111043.347344:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:20480/devtools/browser/77879a64-7b43-4891-98e7-ab996a494c99
[1203/111043.640713:ERROR:backend_impl.cc(1423)] Unable to map Index file
[1203/111043.664279:ERROR:backend_impl.cc(1423)] Unable to map Index file
[1203/111043.665739:ERROR:disk_cache.cc(169)] Unable to create cache
[1203/111043.666072:ERROR:shader_disk_cache.cc(601)] Shader Cache Creation failed: -2
[1203/111044.110259:ERROR:service_manager_context.cc(258)] Attempting to run unsupported native service: /home/wesley/Shared/Chromely/publish/content_renderer.service
[1203/111044.782861:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by mattkol** [comment]
I think this is progress, looks like the fullscreen works in Linux too! Ye!

From experience the error you see can mean many things, but I will suspect the SingleProcess/MultiProcess.

The version you are likely testing with (v66 or lower) allows SingleProcess (not recommended), but allowed. **Note: Looks like the SingleProcess option has been removed for higher versions.**

.NET Core is not that friendly to CEF when you run Multi-process.

The first thing, I will do is try SingleProcess first. So I will uncomment:

 .WithCustomSetting(CefSettingKeys.SingleProcess, true);

More info - https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)

CEF expects a subprocess exe to run multi-process. CefSharp provides a subprocess. Not sure CefGlue does. I have not found any. But if non is provided it defaults to main application exe. Becuase .NET Core does not provide exe when you build, the subprocess is not detected automatically. So to allow a subprocess to be detected, you have to publish the .NET Core app to exe. How to publish is at the bottom of the wiki.

So I will suggest you either try SingleProcess first or you publish for Multiprocess.

Please see where this is pointed out in the wiki.

````csharp
   // The single process should only be used for debugging purpose.
   // For production, this should not be needed when the app is published 

   // Alternate approach for multi-process, is to add a subprocess application
   //.WithCustomSetting(CefSettingKeys.BrowserSubprocessPath, path_to_subprocess)
   .WithCustomSetting(CefSettingKeys.SingleProcess, true)

````

Other issues that could cause this may be how the binaries are installed. The [wiki](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)#on-linux-ubuntu-with-published-self-contained-net-core) details what are needed for proper libcef.so installation. **But I doubt this is the case as it looks like the binaries are loaded correctly.**

Thanks for helping with this.

**Comment by mattkol** [comment]
@WSpadaro I have checked every line of code to see what could be missing or different between old and new. I cannot find anything. 

Meanwhile, I have added the WindowState option to the older code that works - files needed will be - Chromely.Core.Old.dll and Chromely.CefGlue.Gtk.Old.dll in [Binaries folder](https://github.com/mattkol/Chromely/tree/master/binaries).

If this works, I may have to revert back to this. Thanks.

**Comment by WSpadaro** [comment]
@mattkol I have tested using the two Old.dll's and it works. I am able to create a full-screen browser.

**Comment by mattkol** [comment]
@WSpadaro great job! Thanks for the effort.

Any chance on improvement on what was not working?  - [Not Working Yet](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)#not-working-yet). 

I pushed the code that works, let me know if you find anything. I may make few changes here and there between now and the weekend, but they will be minor.

Thanks.
