### ISSUE TITLE
Dev tools

### ISSUE THREAD

**Issue by sambengtson** [mattkol/Chromely#49]
Is it possible to open chrome dev tools for debugging?

**Comment by sambengtson** [comment]
It appears that all web logs are outputted to the dot net console that runs alongside the browser frame 👍

**Comment by sambengtson** [comment]
I'm going to re-open.  The more I think about it, it would be really nice to debug the JS side with chrome dev tools.  I'm trying to figure out how to get a handle on the CEF browser to make this happen.

**Comment by mattkol** [comment]
Sorry about that, I forgot to update a file which broke that. This is now fixed.

The default context menu lets you launch the DevTool if you are in debug mode. However this is customizable. You can either permanently set the mode to debug or register a new context menu handler.

1. Setting debug mode

````csharp
ChromelyConfiguration config = ChromelyConfiguration
                              .Create()
                              .WithDebuggingMode(true)
                              -----
CefGlueSchemeHandlerFactory());
````

2. [Register new handler](https://github.com/mattkol/Chromely/wiki/Configuration#how-to-add-custom-handlers)

![image](https://user-images.githubusercontent.com/18384207/48522205-629e7100-e83d-11e8-8946-edf3307a314b.png)

![image](https://user-images.githubusercontent.com/18384207/48522224-73e77d80-e83d-11e8-91b3-bbf02d0008d5.png)

**Comment by ioanb7** [comment]
Just tried this with the demo setup from the tutorial.

Adding a breakpoint in the javascript from the devtools freezes the entire app - including the devtools itself. It is impossible to go past the breakpoint.

Also the app exits when pressing F12. Didn't use `CefGlueSchemeHandlerFactory`. Adding `debugger` in the JS file has the same result.

How can I get around this?

![image](https://user-images.githubusercontent.com/9282777/49669730-246e2900-fa5a-11e8-811c-aa011e47d243.png)

**Comment by mattkol** [comment]
Any reason for removing CefGlueSchemeHandlerFactory? Did you replace it
with a custom implementation?

CEF is multi-process and can be difficult to debug. The advise is to set it
to SingleProcess for ease of debugging. So yes it is easy to get into an
unstable state when you debug in multi-process, multi-threaded setup.
*Note also that going forward with newer versions SingleProcess will be
removed  *

My advise is to run any of the demos as-is and gradually make changes to
it, until you get familiar with what is needed and what is not.

F12 exiting app? I have never seen that before. You can trap key event by
registering a custom KeyHandler to see what is happening under the hood.
Please see Configuration wiki page on how to do that -
https://github.com/mattkol/Chromely/wiki/Configuration#how-to-add-custom-handlers

Thanks.

**Comment by ioanb7** [comment]
I didn't remove `CefGlueSchemeHandlerFactory`, never added it.

Just ran the code from https://github.com/mattkol/Chromely/wiki/dotnet-cli-Starter-Template 

My Program.cs's Main is:

```
           try
            {
                HostHelpers.SetupDefaultExceptionHandlers();
                string startUrl = "local://app/chromely.html";
                ChromelyConfiguration config = ChromelyConfiguration
                                              .Create()
                                              .WithAppArgs(args)
                                              .WithHostSize(1200, 900)
                                              .WithLogFile("logs\\chromely.cef_new.log")
                                              .WithStartUrl(startUrl)
                                              .WithLogSeverity(LogSeverity.Info)
                                              .UseDefaultLogger("logs\\chromely_new.log")
                                              .UseDefaultResourceSchemeHandler("local", string.Empty)
                                              .UseDefaultHttpSchemeHandler("http", "chromely.com")
                                              .WithCustomSetting(CefSettingKeys.SingleProcess, true)
                                              .WithDebuggingMode(true) // <!-- added this
                                              ;

                var factory = WinapiHostFactory.Init("chromely.ico");
                using (var window = factory.CreateWindow(
                    () => new CefGlueBrowserHost(config),
                    "chromely",
                    constructionParams: new FrameWindowConstructionParams()))
                {
                    window.RegisterUrlScheme(new UrlScheme("https://github.com/mattkol/Chromely", true));
                    
                    window.RegisterServiceAssembly(Assembly.GetExecutingAssembly());
                    
                    string serviceAssembliesFolder = @"C:\ChromelyDlls";
                    window.RegisterServiceAssemblies(serviceAssembliesFolder);

                    // Scan assemblies for Controller routes 
                    window.ScanAssemblies();

                    window.SetSize(config.HostWidth, config.HostHeight);
                    window.CenterToScreen();
                    window.Show();
                    return new EventLoop().Run(window);
                }
            }
            catch (Exception exception)
            {
                Log.Error(exception);
            }

            return 0;```

Demo: https://www.youtube.com/watch?v=WFAh7NRv1Ms

Swapping `.WithCustomSetting(CefSettingKeys.SingleProcess, true)` with `.WithCustomSetting(CefSettingKeys.MultiThreadedMessageLoop, true)` results in:

```
Run 'dotnet [command] --help' for more information on a command.
[1209/150943.246:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[1209/150943.247:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
Unknown option: --type=gpu-process
Unknown option: --no-sandbox
Unknown option: --locales-dir-path=C:\Users\Alex\Documents\Projects\totalaccess\Chromely\bin\x64\Debug\netcoreapp2.1\locales
Unknown option: --log-file=logs\chromely.cef_new.log
Unknown option: --log-severity=info
Unknown option: --resources-dir-path=C:\Users\Alex\Documents\Projects\totalaccess\Chromely\bin\x64\Debug\netcoreapp2.1
Unknown option: --lang=en-US
Unknown option: --gpu-preferences=KAAAAAAAAACAAwCAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAQAAAAoAAAAQAAAAAAAAAAEAAAALAAAA
Unknown option: --use-gl=swiftshader-webgl
Unknown option: --locales-dir-path=C:\Users\Alex\Documents\Projects\totalaccess\Chromely\bin\x64\Debug\netcoreapp2.1\locales
Unknown option: --log-file=logs\chromely.cef_new.log
Unknown option: --log-severity=info
Unknown option: --resources-dir-path=C:\Users\Alex\Documents\Projects\totalaccess\Chromely\bin\x64\Debug\netcoreapp2.1
Unknown option: --lang=en-US
Unknown option: --service-request-channel-token=B24C72A32A369A40C0AB467B2A8AF365
Unknown option: --mojo-platform-channel-handle=1848
.NET Command Line Tools (2.1.500)
Usage: dotnet [runtime-options] [path-to-application] [arguments]
```

Thanks,
Ioan
