### ISSUE TITLE
How to use in. Net Core 2.0

### ISSUE THREAD

**Issue by maikebing** [mattkol/Chromely#5]

**Comment by mattkol** [comment]
I have not done much testing on .NET Core Windows as I thought would be less used on Windows. I have done with Linux, and yet to resolve Linux issue. This is as explained in [Issue #4](https://github.com/mattkol/Chromely/issues/4).

The process for .NET and  .NET Core are pretty the same - creating console apps, but there are a few tweaks.

Please give me a few days to resolve that and I will update wiki.

**Comment by mattkol** [comment]
Recent comment on [CefGlue Linux](https://bitbucket.org/xilium/xilium.cefglue/issues/196/is-it-possible-to-use-net-core-and-deploy) - Comment No. 3

**Comment by mattkol** [comment]
For full description on .NET Core x64 (Windows) please check [Getting Started - CefGlue Winap (.NET Core)](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winap-(.NET-Core)).

Please let me know if you need more info.

**Comment by maikebing** [comment]
It' Cool !Thanks!

**Comment by mattkol** [comment]
Added Linux demo. Please [see](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Gtk-(Linux)) for more info.

**Comment by maikebing** [comment]
OK
