### ISSUE TITLE
corert compiled binaries not working

### ISSUE THREAD

**Issue by jojify** [mattkol/Chromely#53]
I have used CoreRT, (NET Core runtime optimized for AOT ) to build my Chromely sample app. It successfully generated native binaries. But when the executable generated following error. Unable to load DLL 'libcef': specified module is not available.

**Comment by mattkol** [comment]
I am assuming you are building a CefGlue demo.

The error you are seeing means you either have no CEF binaries or the version is wrong. With version v66 and above you do not need to download CEF binaries manually. But you have to use nuget package to do that - [Chromely.CefGlue.Winapi](https://www.nuget.org/packages/Chromely.CefGlue.Winapi). 

To manually download try - [here](https://github.com/mattkol/Chromely/wiki/CefGlue-Application-Layout)

.NET Core wiki - [here](https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core))

A faster way is to try the [cli](https://github.com/mattkol/Chromely/wiki/dotnet-cli-Starter-Template)

**Comment by jojify** [comment]
Thanks a lot for the response.
I used latest pre- release version (Install-Package Chromely.CefGlue.Winapi -Version 68.0.0-pre01).
Please find the attached screenshot.
I followed steps from the link exactly. (https://github.com/mattkol/Chromely/wiki/Getting-Started-CefGlue-Winapi-(.NET-Core)). 
When I build the program using visual studio, it runs perfectly. 

But again when I tried to build using CoreRT, I got the native executable in the native folder. It shows an error:-Value can't be null. parameter name :path1. Please find the attached screen shot.
![sc2](https://user-images.githubusercontent.com/3658295/49860871-a8d8f700-fe20-11e8-83d5-01f549154887.png)
![sh1](https://user-images.githubusercontent.com/3658295/49859167-dc198700-fe1c-11e8-8782-9f575d75dabe.png)

Source code is also attached.
Commands used to execute to build using CoreRT is in the source code folder (CoreRT Build.txt). 
[chromely Sample.zip](https://github.com/mattkol/Chromely/files/2671351/chromely.Sample.zip)

I am trying to build a native application using chromely. It will be great if you can take a look into this.

**Comment by mattkol** [comment]
The error is coming from:

https://github.com/mattkol/Chromely/blob/dae79d3c407fbfe3bfa4b225787571fe84d05ce0/src/Chromely.Core/Infrastructure/SimpleLogger.cs#L59

This happens when an explicit log file name is not provided. 

Looks like a .NET Core unmanaged/managed issue

"The GetEntryAssembly method can return null when a managed assembly has been loaded from an unmanaged application. For example, if an unmanaged application creates an instance of a COM component written in C#, a call to the GetEntryAssembly method from the C# component returns null, because the entry point for the process was unmanaged code rather than a managed assembly."

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=netframework-4.7.2

While an alternative approach is being investigated, please use an explicit log file name like:

````csharp
  .WithLogFile("logs\\chromely.cef_new.log")
````

Meanwhile, I will check for null first before the path is created, which should have been done, notwithstanding, so is a bug in itself.

Thanks for pointing that out!

**Comment by mattkol** [comment]
Or

````csharp
       .UseDefaultLogger("logs\\chromely_new.log")
````

**Comment by jojify** [comment]
I added above mentioned lines and build the solution using CoreRT. it shows the following error. Unable to load DLL 'libcef': The specified module could not be found.	   at ChromelySample!<BaseAddress>+0x17909c
   at ChromelySample!<BaseAddress>+0x178fb9
   at Xilium.CefGlue.Interop.libcef.api_hash(Int32) + 0x3a
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash() + 0x1b
   at Xilium.CefGlue.CefRuntime.Load(String) + 0x3b
   at Chromely.CefGlue.Winapi.BrowserWindow.HostBase.RunInternal(String[]) + 0x39
   at Chromely.CefGlue.Winapi.BrowserWindow.HostBase.Run(String[]) + 0xf
I manually copied libcef to the native folder and run the native binaries. Then it shows the following error.
Operation is not supported on this platform.	   at ChromelySample!<BaseAddress>+0xc656d
   at Chromely.CefGlue.Winapi.BrowserWindow.HostBase.RunInternal(String[]) + 0x81
   at Chromely.CefGlue.Winapi.BrowserWindow.HostBase.Run(String[]) + 0xf

**Comment by mattkol** [comment]
@jojify . remember that is the error you first reported. Please look at my first comment. That is still valid.

These CEF binary files should be in your bin/executing folder at all times. My advise it to copy the binaries into a separate folder and when you build with CoreRT you can always copy them over before starting the app. **Also ensure that the files are the right Version/Platform/CPU.** 

From the link in my first comment, the CEF binary files will be like:

     ![](https://github.com/mattkol/Chromely/blob/master/Screenshots/cef_merged_binaries.png)

**Comment by jojify** [comment]
Sorry that I didn't explain properly. Chromely Winapi .NET Core version is working perfectly for me. I was referring CoreRT runtime.  As MichalStrehovsky said https://github.com/dotnet/corert/issues/6679#issuecomment-446951345 , I was trying to generate single-file executables with no dependencies without using .net core runtime. Anyway  both of your comments will help me to check further on this. Thanks a lot for your feedback.

**Comment by mattkol** [comment]
Thanks for helping improve Chromely. This is significant!
