### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by redradist** [mattkol/Chromely#59]
Hi,

I am curious if Chromely does support Android Platform ?
If no, what is the reason ?

Thanks

**Comment by mattkol** [comment]
No, it does not support Andrioid Platform.
Reason: Scope.
[Chromely Platform support statement](https://github.com/mattkol/Chromely#platforms).

Besides, Chromely relies on .NET Core for cross-platform, and there is [no support yet for Android](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md). Only Windows, Linux and macOS supported, so far.
