### ISSUE TITLE
Error with Angular demo

### ISSUE THREAD

**Issue by artyprog** [mattkol/Chromely#6]
Hello,

Thanks for Chromely
I got the following erreor with angular demo

(xcopy failed)

c:\EXP\Chromely\angular\ChromelyAngularCefGlue\ChromelyAngularCefGlue.csproj(66,7): error MSB3073: La commande "xcopy "c:\EXP\Chromely\angular\ChromelyAngularCefGlue\dist" "c:\EXP\Chromely\angular\ChromelyAngularCefGlue\bin\x64\Debug\net461\dist"   /i /s /r /y /c" s'est arrêtée avec le code 4.
1>Génération du projet "ChromelyAngularCefGlue.csproj" terminée -- ÉCHEC.

Regards

**Comment by mattkol** [comment]
Apologies, I have not had time for wiki on Angular.

There are 2 xcopy tasks in the project, One in the [project file](https://github.com/mattkol/Chromely/blob/master/angular/ChromelyAngularCefGlue/ChromelyAngularCefGlue.csproj) and the [package.json](https://github.com/mattkol/Chromely/blob/master/angular/ChromelyAngularCefGlue/angularapp/package.json) file. From what you sent it looks like this is failing in the project file. It is the post build event task. 
I will suggest that you try the "xcopy" task in the cmd window. 

````csharp
xcopy "c:\EXP\Chromely\angular\ChromelyAngularCefGlue\dist" "c:\EXP\Chromely\angular\ChromelyAngularCefGlue\bin\x64\Debug\net461\dist" /i /s /r /y /c"
````
to make sure that xcopy works on your computer.

Alternatively you can remove the "xcopy" tasks from both files and copy the files  manually. 

You can also comment out the **DebugRunAngularApp** , **ReleaseRunAngularApp** ,  and **PostBuild**  tasks in the project file one at a time ...to track what the issue can be,

The **angularapp** can also be built using Node.js with Visual Studio Code.

Project file:
![issue_angular1](https://user-images.githubusercontent.com/18384207/36926820-ae014ab6-1e47-11e8-8dbf-2571aa38a36b.png)

packakage.json:
![issue_angular2](https://user-images.githubusercontent.com/18384207/36926821-ae154c64-1e47-11e8-93b1-1d1eefb75e86.png)

**Comment by artyprog** [comment]
Tank you vert much
Regards

**Comment by mattkol** [comment]
You are welcome.
Will close this now.
