### ISSUE TITLE
Getting Started Procedure Fails

### ISSUE THREAD

**Issue by johnholliday** [mattkol/Chromely#62]
The getting started steps do not work for Visual Studio 2017. 
1. Create .NET console app targeting x64 .Net Framework 4.7
2. Change project type to "Windows Application"
3. Add Chromely.CefSharp.Winapi (67.0.0-pre01) from Nuget-prerelease
=> Fails to load System.IO.Compression.ZipFile and rolls back
4. Manually install System.IO.Compression.ZipFile from Nuget
5. Add Chromely.CefSharp.Winapi (67.0.0-pre01) from Nuget-prerelease
=> Fails with multiple errors
=> Rolls back

**Comment by mattkol** [comment]
I just tried it and it was successful. Please see attached.
Please ensure that x64 configuration is selected. **It will fail if AnyCPU is selected.** Alternative is to set AnyCPU support flag, but not necessary:

https://github.com/mattkol/Chromely/blob/a3a35ff984908880bd41ba7d72cbca1ddc11ef8d/src/Chromely.CefSharp.Winapi/Chromely.CefSharp.Winapi.csproj#L5

Also note that this is while downloading CEF binaries from CefSharp. If this error persist we may have to chat with the CefSharp group. But it works all the time, though.
[CefSharpTester.zip](https://github.com/mattkol/Chromely/files/2704753/CefSharpTester.zip)

**Comment by johnholliday** [comment]
I tried again and got it to work by following these steps:

1. I created a new blank solution.
2. Instead of a console app, I created a windows forms app targeting .NET v4.61
3. Before adding the nuget packages, I changed the platform configuration to x64 for both the solution and the application.
4. Add the nuget packages as before.
5. Replaced the code in program.cs with code from the winapi demo.

**Comment by mattkol** [comment]
Well I guess that should work too. But Chromely is not intended to be used/embedded in WinForms. The intention from Readme:

... It is focused on building apps based on [Xilium.CefGlue](https://bitbucket.org/xilium/xilium.cefglue/wiki/Home), [CefSharp](https://github.com/cefsharp/CefSharp) implementations of  embedded Chromium ([Cef](https://bitbucket.org/chromiumembedded/cef)) **without WinForms or WPF**. 

But if it works for you, all great!

Thanks.
