### ISSUE TITLE
What is 64 bit windows app zipped size?

### ISSUE THREAD

**Issue by mattkol** [mattkol/Chromely#64]
his 64bit windows app zipped is 66mb, which is not too far from what I would get from electron-builder

_Originally posted by @blurymind in https://github.com/mattkol/Chromely/issues/63#issuecomment-450557231_

**Comment by mattkol** [comment]
@blurymind there is no clear answer to this. Chromely is dependent on CefSharp/CefGlue and CEF binaries. The original sizes of binaries produced by these dependencies are kept. So I will say from experience about 120mb. What Chromely produces itself is under 2mb in most cases. So unless you package Chromely + CefSharp/CefGlue separately and auto download the CEF binaries the first time it is being used by the user, the size will definitely be more than 60mb.

Chromely is more about simplicity rather than weight optimization. But weight optimization can be achieved by either compression/decompression or live download by the user on first installation.

**Comment by pkudrel** [comment]
Hi, 
Thank you for this great project  @mattkol 

I created an example of how to build a "single executable", small, Chromely application that downloads  "Cef" and "CefSharp" files during the first launch.

https://github.com/pkudrel/ChromelySmallSingleExecutable

**Comment by mattkol** [comment]
@pkudrel thanks a lot for sharing this.
Please check that I get the description right - https://github.com/mattkol/Chromely/tree/master/Demos

**Comment by pkudrel** [comment]
Looks good to me.
