### ISSUE TITLE
Are you guys doing the same?

### ISSUE THREAD

**Issue by seriouz** [mattkol/Chromely#7]
Do you know the Neutronium project?

https://github.com/NeutroniumCore/Neutronium

It seems you guys are doing pretty much the same?

**Comment by mattkol** [comment]
Similar but not the same.
Neutronium, I believe is focused on WPF using MVVM pattern.
Chromely lightweight - uses native GUI APIs - Win32, Gtk. Chromely has no support for WPF or WinForms but can be extended by those who may want to do that.

**Comment by seriouz** [comment]
Thanks! Your project looks amazing! It need way more stars and supporters!

**Comment by mattkol** [comment]
Thank you!  Help spread the word. 

Appreciated.
