### ISSUE TITLE
Do you support ios?

### ISSUE THREAD

**Issue by netsmallhao** [mattkol/Chromely#8]

**Comment by mattkol** [comment]
No iOS support.

Chromely is a desktop framework for Windows and Linux. No macOS support too.

**Comment by peternoyes** [comment]
Is macOS a possibility?

**Comment by mattkol** [comment]
Yes, it is possible with .NET Core.

But I don't have experience developing on macOS, so I did not make it a primary focus from the beginning.

Contributions are, of course, welcomed.
