### ISSUE TITLE
Can Visual Studio 2015 be developed?

### ISSUE THREAD

**Issue by zgcwkj** [mattkol/Chromely#9]
Can Visual Studio 2015 be developed?
用Visual Studio 2015可以开发吗？

**Comment by mattkol** [comment]
Chromely was built with VS 2017. I did not test with VS 2015 yet.

However, while looking around, I found useful info from here: https://github.com/dotnet/announcements/issues/24 :

Please check the "Tooling Prerequisites" section.

1. The base framework for Chromely is .NET Standard 2.0 and will require VS 2017 to build.

2. But you can consume .NET Standard 2.0 in VS 2015 so the Demos should work when you rebuild with VS 2015.

The alternative is to convert the projects to .NET Framework but that would limit you to only Windows and you cannot run .NET Core apps.

Pleaae let me if I can help with more info.
